### ISSUE TITLE
openGPG issue linux libopenshot-audio-dev

### ISSUE THREAD

**Issue by ChillerDragon** [OpenShot/libopenshot#477] opened 2020-03-25 19:55 UTC
Following the [instructions from the wiki](https://github.com/OpenShot/libopenshot/wiki/Linux-Build-Instructions#install-dependencies) on debian 10 i  get a openGPG error:

```
$ sudo add-apt-repository ppa:openshot.developers/libopenshot-daily
 This PPA contains the most recent source code from libopenshot (OpenShot Video Library). These packages are only intended for testers of OpenShot 2.0, as the source code can be highly unstable during active development of libopenshot.

If you are looking for daily builds of OpenShot 1.x, please go here: https://code.launchpad.net/~openshot.developers/+archive/daily
 More info: https://launchpad.net/~openshot.developers/+archive/ubuntu/libopenshot-daily
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmp1tdldggc/pubring.gpg' created
gpg: /tmp/tmp1tdldggc/trustdb.gpg: trustdb created
gpg: key 52165BD6B9BA26FA: public key "Launchpad OpenShot Development PPA" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
```

At first I thought its just a warning but doing updates looks bad:

```
$ sudo apt update
[...]                                                       
Err:9 http://ppa.launchpad.net/openshot.developers/libopenshot-daily/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 52165BD6B9BA26FA
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/openshot.developers/libopenshot-daily/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 52165BD6B9BA26FA
E: The repository 'http://ppa.launchpad.net/openshot.developers/libopenshot-daily/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Seems like some security configuration could allow to proceed but I wish there was a better way.

**Comment by ferdnyc** [comment] 2020-03-26 03:18
This is either a local configuration error or a problem with the PPA, which isn't managed in the project repo. That stuff's all external.

I'd suggest reporting this either:
* On Launchpad, I guess probably at https://launchpad.net/~openshot.developers
* On Reddit at https://www.reddit.com/r/OpenShot/

However, it seems like it might be a local configuration issue. You can see from the `add-apt-repository` output where it's importing the key:
```
gpg: keybox '/tmp/tmp1tdldggc/pubring.gpg' created
gpg: /tmp/tmp1tdldggc/trustdb.gpg: trustdb created
gpg: key 52165BD6B9BA26FA: public key "Launchpad OpenShot Development PPA" imported
```
But then it reports "no valid OpenPGP data found.", and later on fails to check that _same_ key:
```
  The following signatures couldn't be verified because the public key is not available:
 NO_PUBKEY 52165BD6B9BA26FA
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/openshot.developers/libopenshot-daily/ubuntu focal
 InRelease: The following signatures couldn't be verified because the public key is not
 available: NO_PUBKEY 52165BD6B9BA26FA
```

Seems like it might be a problem with your local GPG configuration, but I don't run Ubuntu so really I'm pretty clueless about all things apt.

Still, closing as **#SEP**

**Closed by ferdnyc** 2020-03-26 03:18 UTC

**Comment by ferdnyc** [comment] 2020-03-26 03:41
[This page](https://linuxconfig.org/install-packages-from-an-ubuntu-ppa-on-debian-linux#h9-import-the-key) suggests that this command might solve your problem:
```sh
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys \
FBA0C227099A5360635E3D9152165BD6B9BA26FA
```

...Though I'd really have thought `apt-add-repository` should take care of that automatically. (That page is a post on how Debian users, who _don't_ have `add-apt-repository`, can still install packages from Ubuntu PPAs.) Still, couldn't hurt to try.

**Comment by ferdnyc** [comment] 2020-03-26 04:22
Oh, regarding your final question about whether it's possible to install `libopenshot-audio` from source: Absolutely! Just 
````sh
git clone https://github.com/OpenShot/libopenshot-audio
```
Then follow the build and install instructions in the [Linux Build Instructions (libopenshot-audio)](https://github.com/OpenShot/libopenshot/wiki/Linux-Build-Instructions#linux-build-instructions-libopenshot-audio) section of the wiki page.

You can either use `sudo make install` to install the results systemwide, or add `-DCMAKE_INSTALL_PREFIX=<dir>` to the `cmake` command line, run the install without root privileges, and then pass that same location as the `-DOpenShotAudio_ROOT=<dir>` path when generating libopenshot's build environment.

(There's another version of the setup process that goes into more detail on that second option, I think it's in the User Guide. If I find it I'll link that here, too.)

**Comment by ferdnyc** [comment] 2020-03-26 04:25
Yup, the [Developers](https://cdn.openshot.org/static/files/user-guide/developers.html) page in the User Guide is largely a duplicate of the wiki install instructions, but it demonstrates a non-root install for the dependencies.

If you find that [more] useful, and think it should be the preferred version, let me know and I'll sync up the libopenshot wiki install instructions to match.
