### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by toddy15** [OpenShot/libopenshot#69] opened 2017-11-18 12:41 UTC
Hi,

with the current libopenshot 0.1.9 version, the tests still fail at the same stage:

----------------------------
     RUNNING ALL TESTS
----------------------------
[AudioData @ 0x7f9015ff1d20] invalid NULL pointer for src[0]
[AudioData @ 0x7ffe16509af0] invalid NULL pointer for src[0]
[AudioData @ 0x7f90157f0d20] invalid NULL pointer for src[0]
[AudioData @ 0x7f9016ff3d20] invalid NULL pointer for src[0]
[AudioData @ 0x7f9017ff5d20] invalid NULL pointer for src[0]
[AudioData @ 0x7f90177f4d20] invalid NULL pointer for src[0]
[AudioData @ 0x7f9016ff3d20] invalid NULL pointer for src[0]
[libvpx @ 0x56262dfef980] v1.6.1
[webm @ 0x56262e0d54a0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[webm @ 0x56262e0d54a0] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[webm @ 0x56262e0d54a0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[AudioData @ 0x7f9017ff5d20] invalid NULL pointer for src[0]
[AudioData @ 0x7ffe165092f0] invalid NULL pointer for src[0]
/build/libopenshot-0.1.9+dfsg1/tests/FFmpegWriter_Tests.cpp:76:1: error: Failure in FFmpegWriter_Test_Webm: Expected 23 but was 12
/build/libopenshot-0.1.9+dfsg1/tests/FFmpegWriter_Tests.cpp:77:1: error: Failure in FFmpegWriter_Test_Webm: Expected 23 but was 12
/build/libopenshot-0.1.9+dfsg1/tests/FFmpegWriter_Tests.cpp:78:1: error: Failure in FFmpegWriter_Test_Webm: Expected 23 but was 12
[AudioData @ 0x7f9017ff5d20] invalid NULL pointer for src[0]
[AudioData @ 0x7f90177f4d20] invalid NULL pointer for src[0]
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
FAILURE: 1 out of 79 tests failed (3 failures).
Test time: 5.10 seconds.
----------------------------

This is probably related to isssues #43 and #65. Moreover, on Debian's build infrastructure, even more tests fail, see https://buildd.debian.org/status/package.php?p=libopenshot&suite=sid for details. This related to issue #51.

**Comment by ferdnyc** [comment] 2018-06-05 13:25
I can't reproduce, on Fedora building against ffmpeg-4.0 (with my changes from PR #98 applied):
```console
$ make test
Scanning dependencies of target test
----------------------------
     RUNNING ALL TESTS
----------------------------
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
[AudioData @ 0x7ffc479153d0] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc47915d80] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc47915f80] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc47915f80] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc479162e0] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc479162e0] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc479162e0] invalid NULL pointer for src[0]
[libvpx @ 0x217f0c0] v1.7.0
[AudioData @ 0x7ffc479153b0] invalid NULL pointer for src[0]
[libvorbis @ 0x2180280] 31 frames left in the queue on closing
[AudioData @ 0x7ffc47915580] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc479155c0] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc479155c0] invalid NULL pointer for src[0]
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Success: 79 tests passed.
Test time: 6.89 seconds.
----------------------------
Built target test
```

**Comment by ferdnyc** [comment] 2019-07-09 22:58
Closing, please report if you're still experiencing any issues.

**Closed by ferdnyc** 2019-07-09 22:58 UTC
