### ISSUE TITLE
Keyframes and Masks play relative to timeline, not clip

### ISSUE THREAD

**Issue by jeffski** [OpenShot/libopenshot#248] opened 2019-06-11 10:13 UTC
I have noticed an issue with how the timing of keyframes are applied and also a similar issue that means it's not possible to use a video as a mask.

I have found that if you have a clip that starts at position 5 on the timeline, (i.e. it plays from the 5th second on the timeline), if I want to add a keyframe animation to the clip (lets say an alpha change) the first keyframe needs to start at second 5.

This isn't very intuitive as in my mind the keyframe timing should be relative to the clip not the timeline. So the first keyframe should be at 0 to play from the start of the clip.

I guess it's not a deal breaker as I can work around it. It would just be nice if keyframes were relative to the clip they are attached to and not the timeline.

One thing that is not working however is using video (FFMpegReader) in Mask effects. It works fine if the clip the mask is added to starts from 0 on the timeline.

The problem is the mask video seems to play from the start of the timeline so if the mask plays for 5 seconds but the clip starts at 5 seconds then the mask has already finished playing when the clip starts.

I think this is maybe related to keyframes playing relative to the timeline, the mask also plays relative to the timeline but there is no way to adjust it, If the mask played relative to the clip rather than the timeline it should work.

If video masks could be used I think you would be able to create some pretty awesome transitions and effects.

Just posting this now to see if anyone has had the same experience, I'll add some code examples if it helps.

**Comment by SuslikV** [comment] 2019-06-11 15:01
Keyframes curve editor should be implemented first. It is hard to edit something that is not visible.

**Comment by chad3814** [comment] 2019-06-11 15:46
@jeffski I've definitely thought that in the past, but keyframes are definitely defined based on the clip, for example I have a section of code like:
```
    let current_frame = 1;
    for (const clip_data of clip_datas) {
        const clip = new Openshot.Clip(clip_data.resource_name);
        clip.setLayer(3);
        clip.addAlpha(1, 0);
        clip.addAlpha(1 + INTER_CLIP_FADE_DURATION_FRAMES, 1);
        clip.addAlpha(clip.num_frames - INTER_CLIP_FADE_DURATION_FRAMES, 1);
        clip.addAlpha(clip.num_frames, 0);
        timeline.addClip(current_frame, clip);
        current_frame += clip.num_frames;
    }
```
This concatenates a bunch of clips and has them fade to and from black. I've got this other function that given a time in the timeline, finds all the clips from there and beyond that need to be modified, etc.

**Comment by jeffski** [comment] 2019-06-13 00:58
You are right, I tested something similar and also the masks, they all play relative to the clip. Good and bad news - at least it does work correctly but means there is some weird bug in my application that is causing everything to be relative to the timeline. It could be the way I am passing clips around and using pointers, referencing etc...

**Comment by chad3814** [comment] 2019-06-18 17:16
@jeffski what I forgot about when I posted is that the keyframe number is *relative* to the start of the clip, so if you call `clip.Start(5)` then you might think that frame `1` is five seconds into the clip, but it's not. The first frame shown in the timeline is `5 * timeline.info.fps.ToFloat()`. So in that way it is tied to the timeline, and IMHO, oddly. Sorry, I knew I hit something when I read your post.

**Comment by chad3814** [comment] 2019-06-18 18:43
Oh man, the other thing is the frames of keyframes are in terms of the timeline fps; so if your clip fps is 25, and your timeline fps is 30, the frame number 5 seconds into the clip is 151, not 126.

**Comment by jeffski** [comment] 2019-06-24 06:28
> 
> 
> @jeffski what I forgot about when I posted is that the keyframe number is _relative_ to the start of the clip, so if you call `clip.Start(5)` then you might think that frame `1` is five seconds into the clip, but it's not. The first frame shown in the timeline is `5 * timeline.info.fps.ToFloat()`. So in that way it is tied to the timeline, and IMHO, oddly. Sorry, I knew I hit something when I read your post.

Confirming this is the case. It half makes sense, I guess the frame number never changes even if you trim the start of the clip but I think if you trim the start then the frame should be reset to 1, that seems more intuitive.

It's possible to work around that issue by adjusting the frames but I'm not sure about using videos as masks.

See the code below:

```
Timeline timeline(1280, 720, Fraction(25,1), 44100, 2, LAYOUT_STEREO);

Clip clip1(new FFmpegReader("clip1.mp4"));

clip1.Position(0.0);
clip1.Layer(1);
clip1.Start(5.0); // Trim the first 5 seconds of the clip, i.e. start at frame 150

// Setup and add a video mask which is 5 seconds (150 frames) long
Keyframe brightness;
brightness.AddPoint(1, 0);

Keyframe contrast;
contrast.AddPoint(3);

Mask* mask = new Mask(new FFmpegReader("mask.mp4"), brightness, contrast);

clip1.AddEffect(mask);

timeline.AddClip(&clip1);
```

What happens in this case is that the mask is applied at frame 1 and plays for 150 frames, but our clip is trimmed and starts at frame 150 so the mask has finished playing when the clip starts.

Is there a way to work around this? Can effects be added at a specific frame or do they have to apply to the entire clip. Is it possible to use keyframes for the mask itself so it starts at frame 150?

**Comment by chad3814** [comment] 2019-06-24 16:02
I was just looking around and effects have a `Position` because `EffectBase` is a child of `ClipBase`, and `Timeline::apply_effects()` appears to takes that into account:
```
	{
		// Get effect object from the iterator
		EffectBase *effect = (*effect_itr);

		// Does clip intersect the current requested time
		long effect_start_position = round(effect->Position() * info.fps.ToDouble()) + 1;
		long effect_end_position = round((effect->Position() + (effect->Duration())) * info.fps.ToDouble()) + 1;

		bool does_effect_intersect = (effect_start_position <= timeline_frame_number && effect_end_position >= timeline_frame_number && effect->Layer() == layer);
```

**Comment by chad3814** [comment] 2019-06-24 16:11
FWIW, I wish that frame `1` is always the first frame from the clip (or effect), and not the first frame from the clip or effect's underlying resource. Also I wish `Keyframe` frame numbers were based on the underlying resource's FPS, not the `Timeline`'s FPS, because doing effects on the end of the clip is not as clear, you can't rely on `clip.info.length` for example.

But, these changes would be too fundamental and probably break a lot of pre-existing code.

**Comment by jeffski** [comment] 2019-06-25 01:56
I tried to set the effect `Position` but I'm not sure if I'm doing something wrong or there is an issue.

Similar to my previous example:

```
Timeline timeline(1280, 720, Fraction(25,1), 44100, 2, LAYOUT_STEREO);

Clip clip1(new FFmpegReader("clip1.mp4"));

clip1.Position(0.0);
clip1.Layer(1);
clip1.Start(0.0); // Start the clip from the very beginning

Keyframe brightness;
brightness.AddPoint(1, 0.5); // Should appear 0.5 bright from frame 1

Keyframe contrast;
contrast.AddPoint(3);

Brightness effect(brightness, contrast); // Create brightness effect
effect.Position(3); // Would expect the effect to start from the 3rd second of the clip

clip1.AddEffect(&effect);

timeline.AddClip(&clip1);
```

In the example above I've set `effect.Position(3)` and would expect the effect to apply from the third second, however the effect applies from position 0 of the clip.

**Comment by chad3814** [comment] 2019-06-25 14:51
@jeffski that sucks. Maybe @jonoomph has more info/advice?

**Comment by ferdnyc** [comment] 2019-06-26 05:44
Hmm, in the OpenShot GUI effects are attached to an entire clip, all-or-nothing; it's possible this path hasn't been tested much, or makes assumptions based on OpenShot's needs. Still...

What's interesting is to compare `Timeline::apply_effects()` (as quoted by @chad3814 above) with <code><b>Clip</b>::apply_effects()</code>:
https://github.com/OpenShot/libopenshot/blob/a8d545ea92a8a061b0117a2ff6e7a1a78d818c1f/src/Clip.cpp#L1009-L1022

None of the `Position()`/`Start()` checking or any of that. Very much all-or-nothing, just like OpenShot uses it. I have a feeling that's how Clip-attached effects are handled.

But, as @chad3814 showed, the Timeline can also apply effects, and will respect all of the time/position parameters.

@jeffski : what if instead of `clip1.AddEffect(&effect)`, you did this:
```cpp
timeline.AddClip(&clip1);
effect.Layer(1);
effect.Position(3);
timeline.AddEffect(&effect);
```

**Comment by ferdnyc** [comment] 2019-06-26 21:15
(You'd probably also need to set some other parameters for the effect that it would normally pick up from the Clip — Duration/End, at a minimum.)

**Comment by ferdnyc** [comment] 2019-07-09 23:17
Any news on this, OOC? @jeffski?

**Comment by jeffski** [comment] 2019-07-10 02:22
@ferdnyc I got side tracked, let me try and check this out today/tomorrow and see if your work around works.

**Comment by jeffski** [comment] 2019-07-12 05:06
I've tested this and yes, good news, your work around seems to work @ferdnyc. At least I can work with this now. Thanks!

**Comment by ferdnyc** [comment] 2019-07-12 05:31
`\o/`

**Comment by chad3814** [comment] 2019-07-23 00:49
(I apologize for resurrecting a closed issue)
This is an okay work around if you want the effect to apply to the whole view-port, but if you have multiple clips in view at once and only want the effect on the one clip, etc...

Another work around would be to create multiple clips, like you want effect to start 2 seconds in on a clip and last for 3 seconds and then stop, you can create three clips from the same source, setting the start/end times so they line up exactly, and then apply the effect only to the middle one. This is error prone and would be better if the start and end times of the effect (from ClipBase) were honored.

**Comment by ferdnyc** [comment] 2019-07-23 00:57
@chad3814 Not at all, I'm a big fan of thread necromancy. Why cover the same ground over again in a new issue, when we're all on the same page already?

> This is an okay work around if you want the effect to apply to the whole view-port, but if you have multiple clips in view at once and only want the effect on the one clip, etc...

Note that I hadn't tried it, only theorized from reading the code. But, with the `effect.Layer()` property, I would think you could apply the effect to only certain Clips (those on the same layer), without having to attach it to the Clips themselves. Perhaps @jeffski can confirm?

**Comment by jeffski** [comment] 2019-07-23 01:57
Agree, the work around isn't ideal and it would be great if it worked as expected using clips.

This is an example of the work around:

```
Clip clip1(new FFmpegReader("clip1.mp4"));
clip1.Layer(1);
clip1.Position(0);
clip1.Start(0);

Clip clip2(new FFmpegReader("clip2.mp4"));
clip2.Layer(2);
clip2.Position(5);
clip2.Start(3);

Keyframe brightness;
brightness.AddPoint(1, 0);

Keyframe contrast;
contrast.AddPoint(3);

Mask effect(new FFmpegReader("mask.mp4"), brightness, contrast);

effect.Layer(2);
effect.Position(5);
effect.Start(0);
effect.End(clip2.Duration());

timeline.AddClip(&clip1);
timeline.AddClip(&clip2);
timeline.AddEffect(&effect);
```

The `effect` and `clip2` both need to be on the same layer (2) for the effect to work, and this will apply the whole viewport and not the clip if it was resized smaller than the viewport for example.

**Comment by ferdnyc** [comment] 2019-07-23 02:02
> The `effect` and `clip2` both need to be on the same layer (2) for the effect to work

I mean... that part kind of makes sense, in fact it's critical if you're looking to apply effects to only certain clips.

> and this will apply to the whole viewport and not the clip if it was resized smaller than the viewport for example.

That part's a bit of a bummer. Or, perhaps not... I wonder, could you `effect.ScaleX()` / `effect.ScaleY()` it using the same parameters as the clip, in that scenario?

**Comment by jeffski** [comment] 2019-07-23 02:14
I'm not sure I can scale the effect but scaling `clip2` also appears to scale the effect. Does that sound right? That is what I am seeing. I added: 

```
clip2.scale_x.AddPoint(0.5);
clip2.scale_y.AddPoint(0.5);
```

**Comment by ferdnyc** [comment] 2019-07-23 02:14
Another possibility would be to attach the effect to the clip, but keyframe it "off" when you don't want it to be applied. Most effects can be parameterized so they're effectively a no-op. Mask is one of the trickier ones, but since (from the docs) "black is transparent, white is visible", if you _cratered_ the initial brightness all the way down to full `-1`, the mask should end up solid black, and thus invisible. Then you could later keyframe the brightness up to "start" the effect.

**Comment by jeffski** [comment] 2019-07-23 02:16
I think I tried that originally and that works for most effects as far as I remember, the problem with using  video (FFmpegReader) as a mask is that it starts playing straight away so when you make the effect visible the video is already at the end or half way through.

**Comment by ferdnyc** [comment] 2019-07-23 02:18
> I'm not sure I can scale the effect but scaling `clip2` also appears to scale the effect. Does that sound right?

Plausible. Either it literally scales it, **or** just ends up applying the mask to black/transparency, in the areas beyond the clip boundaries — which would similarly be invisible. IOW, sounds like the mask is applied _before_ compositing the other layers, so it wouldn't show up on any part of Layer 2 that's fully transparent, and thus not affect any visible parts of Layer 1.

**Comment by jeffski** [comment] 2019-07-23 02:20
The actual mask looks scaled, I'm using an animated circle shape and can see it has been resized.

**Comment by ferdnyc** [comment] 2019-07-23 02:21
Huh! That's unexpected. But, hey, if it works...

**Comment by ferdnyc** [comment] 2019-07-23 02:25
Hmm. The code does "Resize image to match frame size" — I would've assumed that was the _output_ frame, but perhaps it's the frame size of the clip currently being intersected with the effect.

https://github.com/OpenShot/libopenshot/blob/769efd87e380ea2602348c3f10ecf24fb8304630/src/effects/Mask.cpp#L89-L93

**Comment by ferdnyc** [comment] 2019-07-23 02:29
Actually, I guess that makes sense, because even if you attached the effect to a scaled clip it'd have to do exactly the same thing. Especially if you _can't_ scale an effect. No reason to think the clip would be able to indirectly scale it any more than you could directly, unless scaling was implemented as part of the effect itself.

**Comment by ferdnyc** [comment] 2019-07-23 10:05
> the problem with using video (FFmpegReader) as a mask is that it starts playing straight away so when you make the effect visible the video is already at the end or half way through.

Duh, that also makes sense, yeah.

Still, it sounds like we're back to, "This works exactly like you'd attached the effect directly to a clip, except you can start and stop it at any time you please", no? (FTR, I don't actually think of this as a "workaround", the way I see it attaching effects to clips is the workaround. Or, a "shortcut" implemented for OpenShot. But placing effects directly on layers of the Timeline, complete with their own independent start position and duration, is the more flexible way of handling them, outside of OpenShot's more-limited support.)

**Comment by chad3814** [comment] 2019-07-23 17:01
it requires a sort of re-thinking of how things are interconnected

**Comment by jeffski** [comment] 2019-07-25 23:00
I think I started down the wrong path and started applying effects to clips. You are right, if I start re-thinking around timeline then that will be better.

**Comment by ferdnyc** [comment] 2019-08-05 05:27
Closing this based on @jeffski 's last comment, which as I read it indicates we've settled on **#notabug** (in fact, a feature!) as the ultimate resolution on this. Feel free to reopen if I've overlooked or discounted any remaining issues.

**Closed by ferdnyc** 2019-08-05 05:27 UTC
