### ISSUE TITLE
building install error 

### ISSUE THREAD

**Issue by brcisna** [OpenShot/libopenshot#474] opened 2020-03-21 17:41 UTC
Hello ,

Debian Bullseye (11)

trying to install openshot-qt from this doc:  https://github.com/OpenShot/libopenshot/wiki/Linux-Build-Instructions

The apt-get install openshot-qt dies with the following error :

reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openshot-qt : Depends: python3-openshot but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

When trying to manually install python3-openshot 
reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-openshot : Depends: python3 (>= 3.8~) but 3.7.5-3 is to be installed
E: Unable to correct problems, you have held broken packages.

Any ideas what python reconfiguring needs to be done?

I have been able to build install other dependencies along with manually building libopenshot and libopenshot-audio 

the >> import openshot ,,errors with cannot find libopenshot.so.19 ?

I do have libpython3.8-dev installed. 

Thank You

**Comment by ferdnyc** [comment] 2020-03-21 19:22
Oh, the "No rule to make target doc" thing, that _probably_ means you don't have Doxygen installed. CMake won't even create the doc target unless it finds the dependencies.

The FeatureSummary report that was printed at the end of the `cmake` run should list all of what was and wasn't enabled for the build, based on what it detected on your local system. But you can also type `make help` in the build dir at any time, to get a list of available targets:
```sh
$ make help
The following are some of the valid targets for this Makefile:
... all (the default if no target is provided)
... clean
... depend
... install/strip
... install/local
... install
... list_install_components
... doc
... package
... rebuild_cache
... doxygen
... package_source
... edit_cache
... openshot-example
... openshot
... openshot-html-test
... openshot-player
... openshot_autogen
... pyopenshot_swig_compilation
... pyopenshot
... rbopenshot_swig_compilation
... rbopenshot
... os_test
... openshot-test
... test
```

**Comment by ferdnyc** [comment] 2020-03-21 19:24
(Typing `cmake .` in the build dir will also regenerate the build without deleting the previous cache, which also causes the FeatureSummary to be shown again:)
```sh
$ cmake .
-----------------------------------------------------------------
          Welcome to the OpenShot Build System!

CMake will now check libopenshot's build dependencies and inform
you of any missing files or other issues.

For more information, please visit <http://www.openshot.org/>.
-----------------------------------------------------------------

Generating build files for OpenShot with CMake 3.16.4
  Building libopenshot (version 0.2.5)
  SO/API/ABI Version: 19

-- Looking for system JsonCpp
-- Could NOT find RESVG, using Qt SVG parsing instead (missing: RESVG_LIBRARIES RESVG_INCLUDE_DIRS) 
PYTHON_MODULE_PATH: /home/ferd/rpmbuild/REPOS/libopenshot/build_test/dist/lib64/python3.7/site-packages
-- Ruby executable: /usr/bin/ruby
-- Ruby vendor arch dir: /usr/lib64/ruby/vendor_ruby
-- Ruby include path: /usr/include;/usr/include
-- Doxygen found, documentation target enabled
-- Tests enabled, test executable will be built as tests/openshot-test
-- Cmake 3.11+ detected, enabling 'test' target
-- Displaying feature summary

Build configuration:
-- The following features have been enabled:

 * Documentation, Build API documentation with 'make doc'
 * Testrunner, Run unit tests with 'make test'
 * Unit tests, Compile unit tests for library functions

-- The following OPTIONAL packages have been found:

 * cppzmq
 * PythonInterp (required version >= 3)
 * PythonLibs (required version >= 3)
 * Ruby
 * Doxygen
 * PkgConfig
 * ImageMagick

-- The following RECOMMENDED packages have been found:

 * UnitTest++
   Unit testing framework

-- The following REQUIRED packages have been found:

 * JsonCpp
 * Qt5Widgets
 * Qt5Core
 * Qt5Gui
 * Qt5Network (required version >= 5.13.2)
 * Qt5Multimedia
 * Qt5MultimediaWidgets
 * Qt5
 * FFmpeg
 * Threads
 * OpenMP
 * ZeroMQ
 * SWIG (required version >= 3.0)
 * OpenShotAudio (required version >= 0.2.0)

-- The following features have been disabled:

 * Coverage, analyze test coverage and generate report
 * IWYU (include-what-you-use), Scan all source files with 'iwyu'

-- The following OPTIONAL packages have not been found:

 * RESVG

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ferd/rpmbuild/REPOS/libopenshot/build
```

**Comment by ferdnyc** [comment] 2020-03-21 19:38
> I never see the openshot.pm as your mentioned? probably not without
successful import?

Yeah, sorry, that was just my brainfart. I meant `openshot.py`. The extension `.pm` is for Perl modules. :laughing: 

> installed contents:
> - Install configuration: ""
> -- Up-to-date: /usr/local/include/libopenshot/OpenShotVersion.h
> -- Up-to-date: /usr/local/lib/python3.7/dist-packages/_openshot.so
> -- Up-to-date: /usr/local/lib/python3.7/dist-packages/openshot.py
> -- Up-to-date: /usr/local/lib/libopenshot.so.0.2.5
> -- Up-to-date: /usr/local/lib/libopenshot.so.19
> -- Up-to-date: /usr/local/lib/libopenshot.so
> 
> also when trying to install openshot-qt ifrom the PPA initially in the end
> complains about needing python>.3.8 which i have installed
> libpython3.8-dev as well but appears it tries to install python3.7.x?

Since the PPA installs a python extension module, having `libpython3.8` installed isn't enough — it needs to have the 3.8 _interpreter_ installed as well. You may have the 3.8 library installed, but your default/system Python is still 3.7. (I'm assuming, since that's the version your build of libopenshot linked with, looking at the above file paths.)

I'm not involved with the PPA builds and don't run a Debian-based system myself, but I know that on Fedora, before Python 3.8 became the system default `python3` interpreter, it was installable from a `python38` package that placed a `/usr/bin/python3.8` alongside `/usr/bin/python3` (which was `/usr/bin/python3.7`, at the time.)

Even now, I can install any/all of `/usr/bin/python3.4` through `/usr/bin/python3.9`, separately and together, for use with modules built for different ABIs. Perhaps Debian's package collection has something similar?

**Comment by brcisna** [comment] 2020-03-21 19:49
Frank,

If i do a simple python3  ,,then import openshot   ,it fails,,with the unable to locate libopenshot.so.19  

If i do the pythonpath command you mentioned  PYTHONPATH=src/bindings/python python3

Everything goes smooth.
Is this to be expected?

I've tried learning this a little but is deeper than my pay scale.,,,which is about 0 to nothing. 

Thanks again.

**Comment by ferdnyc** [comment] 2020-03-21 20:31
Not unexpected, for sure. And easily explainable, more importantly.

The issue is that the copy of `_openshot.so` that's in your _normal_ `PYTHONPATH` (the one installed somewhere on the system, in other words) isn't linked with a reachable `libopenshot.so.19`. The one in your build dir is linked with the uninstalled `libopenshot.so` you built, so that one works.

Presumably the one that's failing is `/usr/local/lib/python3.7/dist-packages/_openshot.so`. Like I said, CMake is supposed to relink the files on install, but perhaps that didn't go as planned, or maybe some `apt` operations clobbered parts of your install at some point.

Either way, you can make _sure_ which file is being loaded when you **don't** set the `PYTHONPATH` by asking Python — oh, never mind, actually we know. It's in the traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/openshot.py", line 15, in
<module>
    import _openshot
ImportError: libopenshot.so.19: cannot open shared object file: No such
file or directory
```
So, if you run that same `ldd` command on `/usr/local/lib/python3.7/dist-packages/_openshot.so`, it should show you that it _isn't_ finding `libopenshot.so.19`.

_Why_ it isn't finding it, that's a thornier question. ...One thing that strikes me as odd, it looks like CMake is installing into `/usr/local/lib/`? Is that normal, on Debian? I would've expected it to be installing into `/usr/local/lib/x86_64-linux-gnu/`, since presumably you've built the 64-bit version of the library. But, maybe `/usr/local/` is organized differently?

**Comment by brcisna** [comment] 2020-03-21 21:04
Frank ,

here is the contents of /usr/local/lib/python3.7/dist-packages/

screenshot,
Very strange format. listed only as _pycache_ with a symlink for the openshot.cpython-37.pyc 

Never really dealt with this stuff before,,,which is obvious.

![python3 7](https://user-images.githubusercontent.com/47399290/77236526-65297d00-6b8d-11ea-835a-e706b69ce738.png)

As an aside i did go through the routine start to finish as root,,rather than sudo. It made no difference?
I did notice i had to install numphy,,for something,I wonder if that may have altered something for python behind the scenes?

Thank You

**Comment by ferdnyc** [comment] 2020-03-22 07:47
Whoops, sorry — fell asleep.

`__pycache__` is totally normal, those directories are automatically created by Python to hold byte-compiled copies of Python modules the first time they're run.

Anyway, point is, that's not the _installation_, that's a level below. For that file to be there, `openshot.py` must be (or have been) installed one level up, in the `/usr/local/lib/python3.7/dist-packages/` directory itself. Unlike numpy, libopenshot's bindings don't install as a python package (we're still working on that), so there's no `.dist-info` folder or anything.

What you should see are the same two files from your build dir's `src/bindings/python/`. For instance, here's the complete structure for libopenshot-audio and libopenshot installed on my Fedora system. (The prefix dirs are different, of course, and I've edited out all of the non-relevant directories.)
```sh
$ tree -F /usr/lib64/ |egrep '(openshot|\/$)'
/usr/lib64
├── libopenshot-audio.so -> libopenshot-audio.so.7*
├── libopenshot-audio.so.0.2.0*
├── libopenshot-audio.so.7 -> libopenshot-audio.so.0.2.0*
├── libopenshot.so -> libopenshot.so.19*
├── libopenshot.so.0.2.5*
├── libopenshot.so.19 -> libopenshot.so.0.2.5*
├── python3.7/
│   ├── site-packages/
│   │   ├── openshot.py
│   │   ├── _openshot.so*
│   │   ├── __pycache__/
│   │   │   ├── openshot.cpython-37.opt-1.pyc
│   │   │   ├── openshot.cpython-37.pyc
├── ruby/
│   ├── vendor_ruby/
│   │   └── openshot.so*
```
The two different `__pycache__` files show that I've had different versions of `openshot.py` installed at some point in the past, which byte-compiled to different signatures.

If I were to run `ldd` on the `_openshot.so` you see above — or on the `openshot.so` module in the `vendor_ruby` dir — what it would show is that it's linking with `libopenshot.so.19` and `libopenshot-audio.so.7` from `/usr/lib64/`. That happens automatically, because they're in system locations managed by `ldconfig`. So it knows to link those library SONAMEs to those files, for any shared library request anywhere on the system.
```sh
$ ldconfig -p|grep openshot
	libopenshot.so.19 (libc6,x86-64) => /lib64/libopenshot.so.19
	libopenshot.so (libc6,x86-64) => /lib64/libopenshot.so
	libopenshot-audio.so.7 (libc6,x86-64) => /lib64/libopenshot-audio.so.7
	libopenshot-audio.so (libc6,x86-64) => /lib64/libopenshot-audio.so
```

The reason the `_openshot.so` in my build dir **doesn't** use `/usr/lib64/libopenshot.so.19`, but instead uses <code><var>builddir</var>/src/libopenshot.so</code>, is because by default CMake compiles interdependent `.so` files with an [rpath](http://man7.org/training/download/shlib_dynlinker_slides.pdf) that points to its own builds of those dependencies. Then, during the `make install` process, it relinks the libraries/executables to remove the rpath.

#### Uninstalled files:
```sh
$ cd $BUILDDIR
$ objdump -p src/bindings/python/_openshot.so | egrep 'R[UN]*PATH' | sed -e 's/:/:\n\t\t/'
  RPATH                /home/ferd/rpmbuild/REPOS/libopenshot/build/src:
		/home/ferd/rpmbuild/REPOS/libopenshot-audio/build/dist/lib64:

$ ldd src/bindings/python/_openshot.so | grep openshot| sed -e 's/>/>\n   /'
	libopenshot.so.19 =>
    /home/ferd/rpmbuild/REPOS/libopenshot/build/src/libopenshot.so.19 (0x00007f3da9056000)
	libopenshot-audio.so.7 =>
    /home/ferd/rpmbuild/REPOS/libopenshot-audio/build/dist/lib64/libopenshot-audio.so.7 (0x00007f3da5c06000)

$ objdump -p src/libopenshot.so.19 | egrep 'R[UN]*PATH'                        
  RPATH                /home/ferd/rpmbuild/REPOS/libopenshot-audio/build/dist/lib64:

$ ldd src/libopenshot.so.19 | grep openshot |sed -e 's/>/>\n   /'
	libopenshot-audio.so.7 =>
    /home/ferd/rpmbuild/REPOS/libopenshot-audio/build/dist/lib64/libopenshot-audio.so.7 (0x00007f6ff9a91000)

$ objdump -p src/openshot-example | egrep 'R[UN]*PATH' | sed -e 's/:/:\n\t\t/'
  RPATH                /home/ferd/rpmbuild/REPOS/libopenshot/build/src:
		/home/ferd/rpmbuild/REPOS/libopenshot-audio/build/dist/lib64

$ ldd src/openshot-example | grep openshot | sed -e 's/>/>\n   /'     
	libopenshot.so.19 =>
    /home/ferd/rpmbuild/REPOS/libopenshot/build/src/libopenshot.so.19 (0x00007f2ed43ca000)
	libopenshot-audio.so.7 =>
    /home/ferd/rpmbuild/REPOS/libopenshot-audio/build/dist/lib64/libopenshot-audio.so.7 (0x00007f2ed0f18000)
```
#### Installed files:
```sh
$ objdump -p /usr/lib64/python3.7/site-packages/_openshot.so | egrep 'R[UN]*PATH'

$ ldd /usr/lib64/python3.7/site-packages/_openshot.so | grep openshot
	libopenshot.so.19 => /lib64/libopenshot.so.19 (0x00007faa7bcc5000)
	libopenshot-audio.so.7 => /lib64/libopenshot-audio.so.7 (0x00007faa7b028000)

$ objdump -p /usr/lib64/libopenshot.so.19 | egrep 'R[UN]*PATH'

$ ldd /usr/lib64/libopenshot.so.19 | grep openshot
	libopenshot-audio.so.7 => /lib64/libopenshot-audio.so.7 (0x00007f557beda000)

```
Getting long so I'm gonna break this here...

**Comment by ferdnyc** [comment] 2020-03-22 08:09
So, anyway, as to your setup:
1. Running the **build** as root... well, it certainly isn't _recommended_ (just, as a general, across-the-board Linux security precaution), and it could impact your ability to use the resulting objects as a non-root user. But it's unlikely that's a problem, especially if you're able to use the _un_-installed build. Still, it wouldn't hurt to rebuild everything as non-root at some point, for safety's sake.
1. More likely, the issue is that `/usr/local/lib/libopenshot.so.19` (and `libopenshot-audio.so.7` if it's installed there) simply aren't in your `ldconfig` cache. By default when CMake installs files, no matter where they are, it clears the rpath:

```sh
$ cd $BUILDDIR
$ # (Our ruby build right now has an issue where it always tries to install to the system,
$ # so you'll get permission errors trying to write to /usr when you make install as non-root)
$ cmake -DCMAKE_INSTALL_PREFIX=/tmp/dist -DENABLE_RUBY=0 .
$ make install | grep run
-- Set runtime path of "/tmp/dist/lib64/python3.7/site-packages/_openshot.so" to ""
-- Set runtime path of "/tmp/dist/lib64/libopenshot.so.0.2.5" to ""
```

3. `/usr/local/lib` most likely isn't managed by `ldconfig` on your system; I know it's not on mine. (The list of dirs managed by default is built from files in `/etc/ld.so.conf.d/`, plus systemwide defaults like `/lib/` and `/usr/lib/`.) So, those installed files will have no way of finding the libraries they need.
1. There are a few options to solve that.
    1. You could add a file `/etc/ld.so.conf.d/local.conf` containing `/usr/local/lib`, then regenerate the cache with `sudo ldconfig`, which would add the libraries installed there to the cache.
    1. Or you could run `cmake -DCMAKE_INSTALL_PREFIX=/usr .` in your builddirs, then `sudo make install` to reinstall everything (don't forget libopenshot-audio.so, also!) to an existing system path. (You might still have to re-run `sudo ldconfig` manually, after. If you run it as `sudo ldconfig -v|grep openshot` you should see it linking the library SONAMEs to their fully-versioned names.)
     1. Or, there are ways to get CMake to set an install rpath for library files, but TBH I've never tried doing that. rpath tends to be messy and best avoided for shared libraries installed on the system; better to keep them in standard locations where it's not needed.

**Comment by brcisna** [comment] 2020-03-22 18:59
Thank You very much Frank.,

Am learning something out of this,,, I would simply like to get an actual
system install ,, just so i can say i done it. The latest, AppImage does
appear to be working fine now,,though.

I will go through these steps,,and see how things pan out.

 I do quite a few  history videos,,,so this OpenShot,,,does work great
always learning a few new features as i go,,,Only been using it for 5-6
years now,,and still an amaeture...

**Comment by ferdnyc** [comment] 2020-03-23 00:09
> Am learning something out of this,,, I would simply like to get an actual system install ,, just so i can say i done it.

Yeah, I hear you. Honestly it's no small achievement either. (Not that anyone is likely to recognize that fact, sadly.) There are a _lot_ of dependencies and building the whole mess is... squirrely, to say the least.

Worse for the poor Windows users. I mean, **I'VE** still never succeeded in building libopenshot on Windows, and I've tried _pretty_ hard. (Nor have I ever successfully built an AppImage. But that's because the process there is using 4-year-old tools that are no longer supported, plus it still has a ton of steps that can only succeed on one system in existence, and that's @jonoomph 's build server.)

**Comment by brcisna** [comment] 2020-04-10 00:16
Hi Frank,

How are things going?
Say,,I got openshot to build fine on my debian Bullseye (11) box
Question: Why is it,if I save a custom footer/title template it is still in
the ~/honm/,openshot-qt/title folder even after program is closed,,,when I
open Openshot,all the saved templates are cleared out? I know I done this
in the past but i am thinking there may be like a 'custom' folder you have
to make within the openshot-qt folder. I Googled and couldnt come up with
anything.
Sorry for being a pest,

Thank You,
Barry

**Comment by ferdnyc** [comment] 2020-04-13 20:24
@brcisna Yeah, sorry, turns out that was an OpenShot bug. I've transferred the report to OpenShot/openshot-qt#3375, and my PR to fix it is OpenShot/openshot-qt#3376.

**Comment by ferdnyc** [comment] 2020-04-13 20:57
> Say,,I got openshot to build fine on my debian Bullseye (11) box

Great, glad to hear it! I'm going to close this issue as completed, then, since the only thing remaining as far as I can see is the user title template issue which I've already transferred to the openshot-qt repo. But feel free to reopen if there's anything further.

**Closed by ferdnyc** 2020-04-13 20:57 UTC

**Comment by mkgin** [comment] 2022-09-23 12:48
I ran into this issue when trying to build openshot-qt debian package in bookworm (2.6.1+dfsg1-2) debian testing. 

Removing ruby2.7-dev and ruby-dev packages I had installed stopped the package building process from finding Ruby and trying to build libraries for it and after that, building the package went smoothly.

I know this isn't exactly the topic discussed here, but google led me here when I searched the debhelper error
```openshot.so exists in debian/tmp but is not installed to anywhere``` maybe this helps someone else.
